const predefinedBySlug = {
  'first-tee': {
    id: 1,
    name: 'First Tee',
    category: 'Youth Development',
    raised: '$340,000',
    raised_value: 340000,
    desc: 'Building game changers by introducing young people to golf and its values.',
    icon: '🌱',
    color: '#4A8B4A',
    mission: 'First Tee creates experiences that build character, instill life-enhancing values and promote healthy choices through the game of golf.',
    founded: '1997',
    impact: '10M+ young people served',
    website: 'firsttee.org',
  },
  'folds-of-honor': {
    id: 2,
    name: 'Folds of Honor',
    category: 'Military Families',
    raised: '$520,000',
    raised_value: 520000,
    desc: 'Providing educational scholarships to spouses and children of fallen and disabled service members.',
    icon: '🇺🇸',
    color: '#4A7B8B',
    mission: 'Providing educational scholarships to spouses and children of America\'s fallen and disabled service members.',
    founded: '2007',
    impact: '44,000+ scholarships awarded',
    website: 'foldsofhonor.org',
  },
  'pga-reach': {
    id: 3,
    name: 'PGA REACH',
    category: 'Community Outreach',
    raised: '$280,000',
    raised_value: 280000,
    desc: 'The charitable foundation of the PGA of America, focused on inclusion, impact, and community.',
    icon: '⛳',
    color: '#D4A030',
    mission: 'The charitable foundation of the PGA of America, empowering youth and military to thrive through golf.',
    founded: '2014',
    impact: '100+ community programs',
    website: 'pgareach.org',
  },
  'special-olympics-golf': {
    id: 4,
    name: 'Special Olympics Golf',
    category: 'Adaptive Sports',
    raised: '$190,000',
    raised_value: 190000,
    desc: 'Providing year-round sports training and competition for people with intellectual disabilities.',
    icon: '🏅',
    color: '#8B4A6B',
    mission: 'Providing year-round sports training and athletic competition for children and adults with intellectual disabilities.',
    founded: '1968',
    impact: '5M+ athletes globally',
    website: 'specialolympics.org',
  },
  'st-jude-childrens': {
    id: 5,
    name: "St. Jude Children's",
    category: 'Healthcare',
    raised: '$410,000',
    raised_value: 410000,
    desc: 'Leading the way the world understands, treats and defeats childhood cancer.',
    icon: '❤️',
    color: '#8B4A4A',
    mission: 'Leading the way the world understands, treats and defeats childhood cancer and other life-threatening diseases.',
    founded: '1962',
    impact: '80% survival rate achieved',
    website: 'stjude.org',
  },
  'golf-course-superintendents-environmental': {
    id: 6,
    name: 'Golf Course Superintendents Environmental',
    category: 'Environment',
    raised: '$150,000',
    raised_value: 150000,
    desc: 'Advancing environmentally sound golf course management through research and education.',
    icon: '🌿',
    color: '#4A8B6B',
    mission: 'Advancing environmentally sound golf course management through research and education.',
    founded: '1955',
    impact: '10,000+ courses improved',
    website: 'gcsaa.org',
  },
  'veterans-golf-association': {
    id: 7,
    name: 'Veterans Golf Association',
    category: 'Military Families',
    raised: '$230,000',
    raised_value: 230000,
    desc: 'Using golf to enhance veterans\' physical, mental, social, and emotional well-being.',
    icon: '🎖️',
    color: '#6B7B4A',
    mission: 'Dedicated to promoting the game of golf to veterans and their family members to enhance their physical and mental well-being.',
    founded: '2014',
    impact: '15,000+ veteran members',
    website: 'vgagolf.org',
  },
  'youth-on-course': {
    id: 8,
    name: 'Youth on Course',
    category: 'Youth Development',
    raised: '$175,000',
    raised_value: 175000,
    desc: 'Providing subsidized rounds for young golfers and support for career development.',
    icon: '🧒',
    color: '#4A6B8B',
    mission: 'Providing youth with access to life-changing opportunities through golf with subsidized $5 rounds.',
    founded: '2006',
    impact: '2M+ subsidized rounds',
    website: 'youthoncourse.org',
  },
  'wounded-warrior-project': {
    id: 9,
    name: 'Wounded Warrior Project',
    category: 'Military Families',
    raised: '$380,000',
    raised_value: 380000,
    desc: 'Serving veterans and service members who incurred a physical or mental injury.',
    icon: '💪',
    color: '#8B6B4A',
    mission: 'Honoring and empowering wounded warriors who incurred a physical or mental injury, illnesses, or wound.',
    founded: '2003',
    impact: '200,000+ warriors served',
    website: 'woundedwarriorproject.org',
  },
}

export function getPredefinedCharity(charity) {
  return predefinedBySlug[charity?.slug] || null
}

export function enrichCharity(charity) {
  const preset = getPredefinedCharity(charity)
  if (!preset) return charity

  return {
    ...charity,
    name: preset.name,
    category: preset.category,
    icon: preset.icon,
    founded: preset.founded,
    website: preset.website,
    theme_color: preset.color,
    description: preset.desc,
    mission: preset.mission,
    impact_summary: preset.impact,
    total_raised: preset.raised_value,
    supporter_count: charity?.supporter_count || 0,
    preset_raised_label: preset.raised,
    preset_desc: preset.desc,
    preset_impact: preset.impact,
    preset_color: preset.color,
  }
}

export function enrichCharities(charities) {
  return (charities || []).map(enrichCharity)
}
